.PHONY: all
all: make

make: template.tex
	xelatex Primary-Sec2.tex
#	xelatex template.tex

.PHONY: clean
clean:
	@-rm template.aux template.log template.nav template.out template.snm template.vrb
	@-rm Primary-Sec2.aux Primary-Sec2.log Primary-Sec2.nav Primary-Sec2.out Primary-Sec2.snm Primary-Sec2.vrb
