.PHONY: all
all: make

make: Primary.tex
	xelatex Primary.tex
#	xelatex template.tex

.PHONY: clean
clean:
	@-rm template.aux template.log template.nav template.out template.snm template.vrb
	@-rm Primary.aux Primary.log Primary.nav Primary.out Primary.snm Primary.vrb
